# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g yarn
    - name: yarn install, build
      run: |
        yarn install
        yarn build
        
    - name: delete all but dist and git
      run: |
        find -maxdepth 1 ! -name .git ! -name dist -exec rm -rf {} \;
        
    - name: move all dist to cwd
      run: |
        mv dist/* .
        ls -al
    
    - name: remove empty dir
      run: rmdir dist
        
    - name: Update master
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'alex.dykstra@ncr.com'
        git fetch
        git add *
        git stash
        git checkout master
        git checkout stash -- .
        git commit -m "Updating master"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
    - name: Deploy to Looker Production
      uses: joelwmale/webhook-action@2.0.2
      with:
        # The url to send the webhook event to
        url: https://slalomconsulting.looker.com/webhooks/projects/alexs-great-extension/deploy/branch/master

    
